### PR TITLE
Update .travis.yml for successful build (#3)

### PR DESCRIPTION
**Pull request by danielbayerlein**
* Test Ruby -> ruby-head, 2.3.1, 2.2.5
* Some performance improvements

Fix issue #3.

### CODE REVIEW

**Comment by bootstraponline** [comment]
Awesome work. I'll wait for the `Travis CI build` to finish before merging.

**Comment by bootstraponline** [comment]
FYI I had to rebase the GitHub commits for our internal system so you'll probably have to rebase the PR.

**Comment by bootstraponline** [comment]
Another note `build.sh` is used to spin up a docker container which the tests use. The tests execute successfully on our internal CI.

**Comment by bootstraponline** [comment]
I got this working locally:

- Don't run bundle update, it'll cause issues
- Invoke `build.sh`, this will automagically run rspec

Hopefully the PR will pass if you make the above changes.

**Comment by danielbayerlein** [comment]
@bootstraponline Works this gem with rails 5?

**Comment by bootstraponline** [comment]
> Work this gem with Rails 5?

No, I don't think so.

> I think it only works with Rails 4.x.x - all test passed.

Awesome!! I'll merge this. Thanks for fixing the build.

**Comment by tpickett66** [comment]
I've been trying to get Rails 5 testing working but the tooling we use to simulate travis on Jenkins (`wwtd`) doesn't support the `allow_failures` directives so it's hard to get started on that process.

**Pull request merged**
